import MemberHeader from "@/components/member-header";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { currentUser } from "@clerk/nextjs/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await currentUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <MemberHeader user={JSON.parse(JSON.stringify(user))} />

          {/*Main Content*/}
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
